### ISSUE TITLE
Polling doesn't work as expected

### ISSUE THREAD

**Issue by DanielSWolf** [danielearwicker/computed-async-mobx#10] opened 2017-09-21 07:58 UTC
I realize that this package is meant to be used with MobX. However, I would have expected it to work with manual polling, too.

Consider this Node code:

```js
const { computedAsync } = require('computed-async-mobx');

function delay(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

async function main() {
  const observableValue = computedAsync({
    init: 'initial Value',
    fetch: async () => {
      console.log('fetch called');
      await delay(1);
      return 'final value';
    },
  });

  for (let i = 0; i < 5; i++) {
    console.log('Accessing observableValue twice.');
    console.log('observableValue:', { busy: observableValue.busy, value: observableValue.value });
    await delay(1);
  }
}

main();
```

The output looks like this:

```
Accessing observableValue twice.
fetch called
fetch called
observableValue: { busy: true, value: 'initial Value' }
Accessing observableValue twice.
fetch called
fetch called
observableValue: { busy: true, value: 'initial Value' }
Accessing observableValue twice.
fetch called
fetch called
observableValue: { busy: true, value: 'initial Value' }
Accessing observableValue twice.
fetch called
fetch called
observableValue: { busy: true, value: 'initial Value' }
Accessing observableValue twice.
fetch called
fetch called
observableValue: { busy: true, value: 'initial Value' }
```

Each time I access a property of `observableValue`, its `fetch` function is re-evaluated. That is unfortunate, but probably cannot be helped; after all, when called by non-observed code, `observableValue` has no way of knowing whether `fetch` will return the same value again. What surprises me, though, is that I never get the actual value returned by `fetch`.

If `fetch` has been called in the past and has resolved with a value, I'd expect `observableValue.value` to return that value.

**Comment by danielearwicker** [comment] 2017-09-23 15:50
Interesting question. The plain MobX computed, when its value is read outside of a reactive context, can just execute its evaluation function and returns the result. It avoids using caching because outside of the reactive context there is no listening for change notifications and hence no way to know when the cache is stale.

But in this case we are completely dependent on caching. Building a promise is expensive: it usually means remote calls etc. We must not repeat the network call every time we are asked for a value. But this means we need cache invalidation. We need to know if the observables that provided the data for the remote call are still valid.

Therefore it makes no sense to use this library outside of reactive contexts.

In fact it would be better if this was made clear by throwing a descriptive `Error` if you try to get the value outside of a reactive context.

**Comment by danielearwicker** [comment] 2017-09-23 15:55
If you set up an `autorun` to observe the value, then a non-reactive polling loop such as yours will actually see the expected behaviour, i.e. `value` and `busy` will transition as expected.

But this is a messy leak of inconsistent behaviour. It would make a lot more sense to use MobX consistently to observe those values changing instead of sometimes using polling unnecessarily.

**Comment by danielearwicker** [comment] 2017-10-14 21:35
Closing this given that the suggestion "it would be better if this was made clear by throwing a descriptive Error if you try to get the value outside of a reactive context" is now implemented in the new API.

**Closed by danielearwicker** 2017-10-14 21:35 UTC
